Reddit_Shredder/urls.py
"""
Definition of urls for RedditShredderOauth.
"""

from datetime import datetime

import django.contrib.auth.views
from django.conf.urls import url

import app.views
from app.reddit_connection import reddit_schedule, reddit_connection

# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    url(r'^$', app.views.home, name='home'),
    url(r'^signup/$', app.views.signup, name='signup'),
    url(r'^authorize_callback/$', app.views.authorize_callback,
        name='authorize_callback'),
    url(r'^reddit_api_json/$', reddit_connection.get_json_reddit,
        name='reddit_api_json'),
    url(r'^shredder/$', app.views.shredder, name='shredder'),
    url(r'^shredder/shred/$', app.views.shredder_output,
        name='shredder_output'),
    url(r'^shredder/run/$', reddit_connection.run_shredder, name='run_shredder'),
    url(r'^profile/$', app.views.profile, name='profile'),
    url(r'^profile/scheduler/$', reddit_schedule.change_schedule,
        name='scheduler'),
    url(r'^profile/privacy/$', app.views.privacy, name='privacy'),
    url(r'^profile/karma_limit/$', app.views.karma_exclude,
        name='karma_limit'),
    url(r'^profile/delete/$', app.views.delete, name='delete'),
    url(r'^profile/logs/$', app.views.logs, name='logs'),
    url(r'^profile/exclude/$', app.views.manual_exclude, name='exclude'),
    url(r'^profile/delete_account/$', app.views.delete_account,
        name='delete_account'),
    url(r'^changelog/$', app.views.changelog, name='changelog'),
    url(r'accounts/login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
                {
                    'title': 'Log in',
                    'year': datetime.now().year,
                    'message': 'Please Login to Continue'
                }
        }),

    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
                {
                    'title': 'Log in',
                    'year': datetime.now().year,
                }
        },
        name='login'),
    url(r'^login/signup/$', app.views.signup),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
]

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.utils.translation import ugettext_lazy as _

from app.models import *


class BootstrapAuthenticationForm(AuthenticationForm):
    """
    Authentication form which uses boostrap CSS.
    """
    username = forms.CharField(label=_('username'),
                               max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder': 'Password'}))


class RedditShredderForm(forms.Form):
    """
    Receives the user's preferences for the manual shredder.
    """

    # The account the user wants to shred (reddit_user_name).
    account = forms.ModelChoiceField(queryset=RedditAccounts.objects.none(),
                                     label=_('Select an Account'),
                                     required=False,
                                     widget=forms.Select({
                                         'class': 'form-control',
                                     }))

    def __init__(self, user_id, *args, **kwargs):
        """
        Extends the ShredderForm class to allow user_name to be selected and
        displayed dynamically in the form.

        :param user_id: The user's id.
        :param args: *
        :param kwargs: **
        """
        super(RedditShredderForm, self).__init__(*args, **kwargs)
        self.fields['account'].queryset = RedditAccounts.objects.filter(
            user_id=user_id).values_list('reddit_user_name', flat=True)

    # The time cut-off to limit the shredder.
    keep = forms.IntegerField(label=_('Time delay in hours'),
                              initial=0,
                              widget=forms.NumberInput({
                                  'class': 'form-control',
                                  'placeholder': 'Time Delay in Hours'
                              }))

    # The user's karma threshold preference.
    karma_limit = forms.IntegerField(label=_('Karma Threshold'),
                                     initial=1,
                                     widget=forms.NumberInput({
                                         'class': 'form-control',
                                         'placeholder': 'Karma Threshold',
                                     }))

    delete_everything = forms.BooleanField(label=_('Delete Everything?'),
                                           required=False,
                                           widget=forms.CheckboxInput({
                                               'class': 'form-control'
                                           }))


class KarmaExcludeForm(forms.ModelForm):
    """
    Allows user's to set a Karma threshold.
    """

    # Create the form from the user's profile.
    class Meta:
        model = Profile
        fields = ['karma_exclude']
        labels = ({'karma_exclude': _('Karma Amount to Exclude')})
        widgets = {
            'karma_exclude': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Karma'
            })
        }


class SchedulerForm(forms.ModelForm):
    """
    Allows user's to set auto-shred schedules for their accounts.
    """
    # Blank IntegerField to receive the comment / submission ID.
    object_id = forms.IntegerField()

    class Meta:
        model = RedditAccounts
        fields = ['schedule']
        labels = ({'schedule': _('Set Schedule')})
        widgets = {
            'schedule': forms.Select(attrs={
                'class': 'form-control',
            }),
        }


class RecordKeepingForm(forms.Form):
    """
    Allows user's to set their record keeping preferences.
    """
    CHOICES = (
        (True, 'Yes'),
        (False, 'No')
    )

    record_keeping = forms.ChoiceField(
        label=_("Privacy Setting"),
        required=True,
        widget=forms.Select(attrs={
            'class': 'form-control',
        }),
        choices=CHOICES,
    )


class UserCreateForm(UserCreationForm):
    """
    Overrides the builtin user creation form, adding email support.
    """
    # declare the fields you will show
    username = forms.CharField(label=_("Your Username"),
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Username'}))
    # first password field
    password1 = forms.CharField(label=_("Your Password"),
                                widget=forms.PasswordInput({
                                    'class': 'form-control',
                                    'placeholder': 'Password'}))
    # confirm password field
    password2 = forms.CharField(label=_("Repeat Your Password"),
                                widget=forms.PasswordInput({
                                    'class': 'form-control',
                                    'placeholder': 'Confirm your password'}))
    email = forms.EmailField(label=_("Email Address"),
                             required=True,
                             widget=forms.EmailInput({
                                 'class': 'form-control',
                                 'placeholder': 'Email'}))

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

    def save(self, commit=True):
        """
        Extends the base user model to include the email field.
        :param commit: True / False.
        :return: The modified user model.
        """
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]

        if commit:
            user.save()

        return user


class ExclusionSelector(forms.Form):
    """
    Allows user's to select specific posts to exclude from the auto-shredder.
    """
    object_id = forms.IntegerField()
    exclude = forms.BooleanField(required=False)

templates/changelog.html
{% extends "layout.html" %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <p class="lead">
                    This page is a log of all the changes made to the shredder since Dec 25, 2017.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th style="width: 120px;">Date</th>
                            <th>Change</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>Jan 9, 2018</td>
                            <td>
                                Holy heck, I really screwed up the logic on the shredder somehow, it's fixed now.
                            </td>
                        </tr>
                        <tr>
                            <td>Jan 7, 2018</td>
                            <td>
                                Fixed an error where the default karma exclude value caused nothing to be deleted.
                                Fixed link on front page, now it links to the Reddit authorization page.
                            </td>
                        </tr>
                        <tr>
                            <td>Jan 3, 2018</td>
                            <td>
                                Added error handling to authorize_callback requests. Now, if a user clicks 'deny' an
                                appropriate error message is shown.
                            </td>
                        </tr>
                        <tr>
                            <td>Jan 3, 2018</td>
                            <td>
                                Added favicon and app manifest.
                            </td>
                        </tr>
                        <tr>
                            <td>Jan 3, 2018</td>
                            <td>
                                Another major update: all profile forms are now dynamic, and the ability to manually
                                delete your ORS account has been added. The index page has been brushed up. I'd like
                                to thank an anonymous Reddit user for their detailed and thorough QA work on the site
                                and its design.
                            </td>
                        </tr>
                        <tr>
                            <td>Jan 2, 2018</td>
                            <td>
                                Total restructure of the manual shredder to accommodate the new internal API system.
                                More info on this change is available at <a
                                    href="https://github.com/simeon4110/reddit-shredder-master">
                                https://github.com/simeon4110/reddit-shredder-master</a>. The new manual shredder
                                can be used by registered users as well as un-registered users.
                            </td>
                        </tr>
                        <tr>
                            <td>Jan 1, 2018</td>
                            <td>
                                Re-built the Reddit API hander into a fully stateless internal API. This allows for
                                AJAX use in the front-end (i.e. fancy loading screens.)
                            </td>
                        </tr>
                        <tr>
                            <td>Dec 31, 2017</td>
                            <td>
                                Added link in top menu to github error reporting page.
                            </td>
                        </tr>
                        <tr>
                            <td>Dec 31, 2017</td>
                            <td>
                                Fixed issue where all Reddit tokens were being verified dozens of times per operation.
                            </td>
                        </tr>
                        <tr>
                            <td>Dec 30, 2017</td>
                            <td>
                                Removed unneeded cache clearing from exclusions.
                            </td>
                        </tr>
                        <tr>
                            <td>Dec 30, 2017</td>
                            <td>
                                Added custom error handling to take care of Reddit API authorization errors, and errors
                                related to remote problems (i.e. issues on Reddit's end.)
                            </td>
                        </tr>
                        <tr>
                            <td>Dec 30, 2017</td>
                            <td>
                                Fixed sessions issues, added manual session purging, ensure sessions are purged on
                                browser close.
                            </td>
                        </tr>
                        <tr>
                            <td>Dec 30, 2017</td>
                            <td>Total reformat of shredder page to provide clarity of use and instructions.</td>
                        </tr>
                        <tr>
                            <td>Dec 30, 2017</td>
                            <td>Added a number of recommendations from an anonymous user.</td>
                        </tr>
                        <tr>
                            <td>Dec 30, 2017</td>
                            <td>Added explicit daily full purge of cache DB.</td>
                        </tr>
                        <tr>
                            <td>Dec 30, 2017</td>
                            <td>Rewrite of cache purging done.</td>
                        </tr>
                        <tr>
                            <td>Dec 30, 2017</td>
                            <td>Added Karma to manual exclusions and deletions.</td>
                        </tr>
                        <tr>
                            <td>Dec 30, 2017</td>
                            <td>Added this page.</td>
                        </tr>
                        <tr>
                            <td>Dec 30, 2017</td>
                            <td>Added logging to reddit_connection module.</td>
                        </tr>
                        <tr>
                            <td>Dec 30, 2017</td>
                            <td>Fixed API token validation errors, added a logic gate to prevent invalid tokens from
                                breaking the auto shredder.
                            </td>
                        </tr>
                        <tr>
                            <td>Dec 28, 2017</td>
                            <td>Updated all DataTables to be responsive.</td>
                        </tr>
                        <tr>
                            <td>Dec 26, 2017</td>
                            <td>Added labels to forms for a better experience for those who use screen readers.</td>
                        </tr>
                        <tr>
                            <td>Dec 25, 2017</td>
                            <td>All shredder logic has been verified and implemented.</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block scripts %}

    {% load staticfiles %}

{% endblock %}

templates/delete.html
{% extends "layout_profile.html" %}

{% block content %}

    <div class="container-fluid">
        <div class="row card-columns">
            <div class="card bg-primary mx-4">
                <div class="card-header">Instructions:</div>
                <div class="card-body">
                    <p class="card-text">
                        To manually overwrite and delete a comment, simply click on the red
                        <span class="oi oi-x"></span> next to the comment you wish to delete.
                    </p>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row mt-3">
                <div class="col table-responsive">
                    {% csrf_token %}
                    <table id="delete" class="table-hover order-column" cellspacing="0" cellpadding="0" width="100%">
                        <thead class="mt-2">
                        <tr>
                            <th></th>
                            <th>Comment Body</th>
                            <th>Karma</th>
                            <th>User Name</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block scripts %}

    {% load staticfiles %}
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/jq-3.2.1/dt-1.10.16/r-2.2.1/datatables.min.js">
    </script>
    <script>
        /* Function to pull reddit API data via internal API request, request must be passed by authed user */
        $(document).ready(function () {
            $('#delete').DataTable({
                'autoWidth': true,
                'responsive': true,
                'processing': true,
                /* Adds the slick gear animation */
                'language': {
                    processing: '<i class="fa fa-gear fa-spin fa-3x fa-fw"></i><span class="sr-only bg-primary"></span> '
                },
                'ajax': {
                    'url': '{% url 'reddit_api_json' %}',
                    'dataSrc': ''
                },
                'columns': [
                    {
                        "data": "cid",
                        /* Creates the links for the POST delete */
                        "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                            $(nTd).html("<a href='?delete=" + oData.cid + "&user_name=" + oData.user_name
                                + "&item_type=" + oData.item_type + "'>"
                                + "<button class='btn btn-danger'>"
                                + "<span class='oi oi-x'></span></button></a>");
                        }
                    },
                    {"data": "body"},
                    {"data": "karma"},
                    {"data": "user_name"}
                ]
            });
        });
    </script>

{% endblock %}

templates/exclude.html
{% extends "layout_profile.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row card-columns">
            <div class="card bg-primary mx-4">
                <div class="card-header">Instructions:</div>
                <div class="card-body">
                    <p class="card-text">
                        To add an item to your list of exclusions click the plus symbol next to the item you wish to
                        add.<br/>
                        To remove an item from your list of exclusions click the minus symbol next to the item you wish
                        to remove.<br/>
                        To sort the list, click the column header that you would like to sort by.
                    </p>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row mt-3">
                <div class="col table-responsive">
                    <table id="exclude" class="table-hover order-column" cellspacing="0" cellpadding="0" width="100%">
                        <thead>
                        <tr>
                            <th></th>
                            <th>Comment Body / Post Title</th>
                            <th>Karma</th>
                            <th>User Name</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}

    {% load staticfiles %}
    <script type="text/javascript"
            src="https://cdn.datatables.net/v/bs4/dt-1.10.16/b-1.5.1/b-colvis-1.5.1/fh-3.1.3/r-2.2.1/datatables.min.js">
    </script>
    <script>
        var excluded = {{ excluded|safe }}
            $(document).ready(function () {
                $('#exclude').DataTable({
                    'autoWidth': true,
                    'responsive': true,
                    'processing': true,
                    /* Adds the slick gear animation */
                    'language': {
                        processing: '<i class="fa fa-gear fa-spin fa-3x fa-fw"></i><span class="sr-only bg-primary"></span> '
                    },
                    'ajax': {
                        'url': '{% url 'reddit_api_json' %}',
                        'dataSrc': ''
                    },
                    'columns': [
                        {
                            'data': 'cid',
                            /* Creates the links for the set / unset POST functions */
                            'fnCreatedCell': function (nTd, sData, oData, iRow, iCol) {
                                if (excluded.indexOf(oData.cid) == -1) {
                                    $(nTd).html("<a href='?set=" + oData.cid + "'>"
                                        + "<button class='btn btn-success'>"
                                        + "<span class='oi oi-plus'></span></button></a>");
                                } else {
                                    $(nTd).html("<a href='?unset=" + oData.cid + "'>"
                                        + "<button class='btn btn-danger'>"
                                        + "<span class='oi oi-minus'></span></button></a>");
                                }
                            }
                        },
                        {"data": "body"},
                        {"data": "karma"},
                        {"data": "user_name"}
                    ]
                });
            });
    </script>

{% endblock %}

templates/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log Out</a></li>
    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log In</a></li>
</ul>

{% endif %}

templates/shredder.html
{% extends "layout.html" %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <p class="lead">
                    This Online Reddit Shredder (ORS) works with OAuth access tokens. to use it, you must first give
                    the app access to your Reddit account. This access can be revoked manually
                    <a href="https://www.reddit.com/prefs/apps/">here</a>, (there is a reminder to revoke access on the
                    output page) and gives access to your identity and posts/comments. Mod related info is not
                    accessible via this token. If you don't want to give me access, please visit the github link on the
                    <a href="{% url 'home' %}">Home Page</a>.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col" style="text-align: center">
                <p class="lead">
                    <strong>Please Authorize the Shredder to Continue:</strong>
                </p>
                <div class="col">
                    <p><a class="btn btn-primary" href="{{ auth }}">Authorize the Shredder &raquo;</a></p>
                </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}

    {% load staticfiles %}

{% endblock %}

templates/shredder_working.html
{% extends "layout.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row card-columns">
            <div class="card bg-danger mx-4">
                <div class="card-header">Important Notes:</div>
                <div class="card-body">
                    <p class="card-text">
                        To delete <strong>everything</strong> enter -24 (i.e. negative 24) into "Hours to Keep."<br/>
                        {% if user.is_authenticated %}
                            <strong>Registered Users: </strong> The manual shredder (i.e. this page) DOES NOT include
                            any
                            comments / submissions you've added to your manual exclusions; if you want these included
                            you
                            MUST use the automatic shredder.
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
        <div class="row card-columns">
            <div class="card bg-primary mx-4 mb-3">
                <div class="card-header">Instructions:</div>
                <div class="card-body">
                    <p class="card-text">
                        To save some of your posts (i.e. the last day's worth of posts and comments) enter the number
                        of hours you'd like to exclude below. For example, to save one full days worth of posts enter
                        "24" to save a week's worth enter "168."
                    </p>
                </div>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-3 col-centered">
                <form action="shred/" method="post" class="form-horizontal">
                    {% csrf_token %}
                    {% if user.is_authenticated %}
                        <div class="form-group">
                            <label for="id_account" class="control-label">Select an Account: </label>
                            {{ form.account }}
                        </div>
                    {% endif %}
                    <div class="form-group">
                        <label for="id_keep" class="control-label">Hours to Keep: </label>
                        {{ form.keep }}
                    </div>
                    <div class="form-group">
                        <label for="id_karma" class="control-label">Karma Threshold: </label>
                        {{ form.karma_limit }}
                    </div>
                    <div class="form-group">
                        <label for="id_karma" class="control-label">Delete Everything? </label>
                        {{ form.delete_everything }}
                        {% if user.is_authenticated is False %}
                            <input type="hidden" name="account" value="None"/>
                        {% endif %}
                        <input type="submit" value="Shred My Account &raquo;" class="btn btn-warning mt-3"/>
                    </div>
                </form>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-12 mt-3">
                <h4 class="display-5 text-danger" style="text-align: center">
                    THERE IS NO WAY TO STOP THIS PROCESS ONCE IT STARTS, DO NOT CLICK THE BUTTON UNLESS YOU ARE SURE YOU
                    WANT TO DELETE ALL YOUR POSTS AND SUBS!!!!
                </h4>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}

    {% load staticfiles %}
    <script src="{% static 'scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

templates/signup.html
{% extends "layout.html" %}

{% block content %}
    <div class="container-fluid">
    <div class="row">
        <div class="col">
            <p class="lead">
                Enter your details below. I will not sell, trade, or otherwise transmit your data. But, as
                this app is in alpha and not a lot of testing has been done on the database security, I wouldn't
                use any credentials shared with other sites.
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <h4 class="display-6">Create an Account:</h4>
            <form action="." method="post" class="form mx-3">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_username" class="control-label">User name:</label>
                    {{ form.username }}
                </div>
                <div class="form-group">
                    <label for="id_email" class="control-label">Email:</label>
                    {{ form.email }}
                </div>
                <div class="form-group">
                    <label for="id_password2" class="control-label">Password:</label>
                    {{ form.password1 }}
                </div>
                <div class="form-group">
                    <label for="id_password1" class="control-label">Confirm:</label>
                    {{ form.password2 }}
                </div>
                <div class="form-group">
                    <input type="hidden" name="next" value="/profile"/>
                    <input type="submit" value="Register &raquo;" class="btn btn-primary"/>
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <h4 class="display-6 mb-3">Donate:</h4>
            <p style="font-size: 16px">
                Want to support this project? Consider making a donation!
            </p>
            <p>Bitcoin (BTC): <a href="bitcoin:1NGacpNa8ysrYgyfBC3rzRP7dKFBWuHZQ8">
                1NGacpNa8ysrYgyfBC3rzRP7dKFBWuHZQ8</a></p>
            <p>Ethereum (ETH): <a href="ethereum:0x5523D17695b5367367697Bebf2AB14aA985fD98A">
                0x5523D17695b5367367697Bebf2AB14aA985fD98A</a></p>
            <p>Litecoin (LTC): <a href="litecoin:LgF5yAoQUtxxCTZijidH9fkX4UcNELzddY">
                LgF5yAoQUtxxCTZijidH9fkX4UcNELzddY</a></p>
            <p style="font-size: 16px">
                All donations are greatly appreciated, and will go to support the hosting costs this project
                incurs.
            </p>
        </div>
    </div>
    </div>

{% endblock %}

{% block scripts %}

    {% load staticfiles %}
    <script src="{% static 'scripts/jquery.validate.min.js' %}"></script>

{% endblock %}